// Objective-C API for talking to foxwallet Go package.
//   gobind -lang=objc foxwallet
//
// File is generated by gobind. Do not edit.

#ifndef __Fox_H__
#define __Fox_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class FoxResult;

@interface FoxResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull data;
@property (nonatomic) NSString* _Nonnull error;
@end

FOUNDATION_EXPORT NSString* _Nonnull FoxErr(NSError* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull FoxOk(NSString* _Nullable data);

FOUNDATION_EXPORT NSString* _Nonnull FoxSpaceMeshAddressFromPubKey(NSString* _Nullable pubHex);

FOUNDATION_EXPORT NSString* _Nonnull FoxSpaceMeshCreateTransaction(NSString* _Nullable pk, NSString* _Nullable to, NSString* _Nullable amountStr, NSString* _Nullable nonceStr, NSString* _Nullable gasPriceStr, NSString* _Nullable genesisID);

FOUNDATION_EXPORT NSString* _Nonnull FoxSpaceMeshSelfSpawnTx(NSString* _Nullable pk, NSString* _Nullable nonceStr, NSString* _Nullable gasPriceStr, NSString* _Nullable genesisID);

FOUNDATION_EXPORT NSString* _Nonnull FoxSpaceMeshStringToAddress(NSString* _Nullable address);

#endif
