
// Objective-C API for talking to the following Go packages
//
//	foxwallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __GoCore_FRAMEWORK_H__
#define __GoCore_FRAMEWORK_H__

#include "Fox.objc.h"
#include "Universe.objc.h"

#endif
